### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by THEYAKUZI** [TurtleTeam/MurderMysteryPE#4]
How to use this plugin I write /newgame but its just keep saying usage /newgame I also tried to write there the world name but nothing happening

**Comment by xBeastMode** [comment]
Bruh, this plugin is work in progress (WIP). Don't you see it in the `README.md`? If you don't know Google it. :tongue:

**Comment by THEYAKUZI** [comment]
Okay you gonna finish this plugin after 5 years?

**Comment by xBeastMode** [comment]
It's not like we can work on this shit 24/7. If you want it so bad why not do it yourself?
